#!/usr/bin/env python3

from modules.connections import bot_token as bot_token
from modules.connections import database_file as database_file
from discord.ext import commands
import aiosqlite
import sys
import os

from modules import first_run


user_extensions_directory = "user_extensions"

if not os.path.exists('data'):
    print("Please configure this bot according to readme file.")
    sys.exit("data folder and it's contents are missing")
if not os.path.exists(user_extensions_directory):
    os.makedirs(user_extensions_directory)

if os.environ.get('GOLIVE_PREFIX'):
    command_prefix = os.environ.get('GOLIVE_PREFIX')
else:
    command_prefix = "/"

first_run.ensure_tables()

initial_extensions = [
    "cogs.AudioStream",
]


class DiscordLinuxGoLiveAudioWorkaroundBot(commands.Bot):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.background_tasks = []
        self.app_version = (open(".version", "r+").read()).rstrip()
        self.description = f"DiscordLinuxGoLiveAudioWorkaroundBot {self.app_version}"
        self.database_file = database_file

        for extension in initial_extensions:
            try:
                self.load_extension(extension)
            except Exception as e:
                print(e)
        for user_extension in os.listdir(user_extensions_directory):
            if not user_extension.endswith(".py"):
                continue
            extension_name = user_extension.replace(".py", "")
            try:
                self.load_extension(f"{user_extensions_directory}.{extension_name}")
                print(f"User extension {extension_name} loaded")
            except Exception as e:
                print(e)

    async def start(self, *args, **kwargs):
        self.db = await aiosqlite.connect(database_file)

        await super().start(*args, **kwargs)

    async def close(self):
        # Cancel all Task object generated by cogs.
        # This prevents any task still running due to having long sleep time.
        for task in self.background_tasks:
            task.cancel()

        # Close connection to the database
        await self.db.close()

        # Run actual discord.py close.
        await super().close()

    async def on_ready(self):
        print("Logged in as")
        print(self.user.name)
        print(self.user.id)
        print("------")
        await first_run.add_admins(self)


client = DiscordLinuxGoLiveAudioWorkaroundBot(command_prefix=command_prefix)
client.run(bot_token)
